spring:
  application:
    name: ai-agent
  profiles:
    active: local
  ai:
    vectorstore:
      pgvector:
        index-type: HNSW
        dimensions: 1536
        distance-type: COSINE_DISTANCE
        max-document-batch-size: 10000
    mcp:
      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:8127
        stdio:
          servers-configuration: classpath:mcp-servers.json

server:
  port: 8123
  servlet:
    context-path: /api

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zyx.aiagent.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
app:
  pgvector:
    enabled: false
