spring:
  application:
    name: ai-agent
  ai:
    dashscope:
      api-key: sk-ddb9be27dddb4081b3e85a07908d0e00
      chat:
        options:
          model: qwen-plus
  datasource:
    url: jdbc:postgresql://rm-cn-3ol4r4e9n0001yzo.rwlb.rds.aliyuncs.com:5432/ai_agent
    username: my_user
    password: T789123TABC!
search-api:
  api-key: dRuV4S4TyEaetN6x2Ess95B7